### ISSUE TITLE
[Suggestion] Let us upload capes bigger than 1024 x 512

### ISSUE THREAD

**Issue by Wide-Cat** [MeteorDevelopment/meteor-bot#11]
I would like to upload capes at a higher resolution than 1024 x 512, as it is possible to do so on other platforms so it should hopefully be also possible here. 🙏

**Comment by seasnail8169** [comment]
Its not that its impossible, its just that we decided thats a reasonable limit for cape sizes, im sure you understand that capes 
1. are files that need to be stored
2. are images that have to be rendered by clients

both of these make higher res capes less desirable

**Comment by seasnail8169** [comment]
@Wide-Cat move this to [MeteorDevelopment/meteor-server](https://github.com/MeteorDevelopment/meteor-server)
